---
apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "20"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: after-workflow
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  entrypoint: argosay
  templates:
    - name: argosay
      container:
        name: main
        image: docker/whalesay:latest
        command:
          - bash
          - -c
        args:
          - "sleep 10 && echo hey"
---
